# This file records information about this repo. Its use is described in OEP-55:
# https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'credentials'
  description: 'The Open edX Credentials Service, which supports course and program certificates.'
  links:
    - url: 'https://edx-credentials.readthedocs.io/'
      title: 'Documentation'
      icon: 'Article'
  annotations:
    # (Optional) Annotation keys and values can be whatever you want.
    # We use it in Open edX repos to have a comma-separated list of GitHub user
    # names that might be interested in changes to the architecture of this
    # component.
    openedx.org/arch-interest-groups: ""
    # This can be multiple comma-separated projects.
    openedx.org/add-to-projects: "openedx:23"
    openedx.org/release: "master"
spec:
  type: 'service'
  lifecycle: 'production'
  owner: 2U-aperture
