comment: false
coverage:
  status:
    patch:
      default:
        target: 95
    project:
      default:
        target: 95
ignore:
  - credentials/settings/production.py
  - credentials/settings/devstack.py
  - credentials/apps/core/management/commands/sync_lms_user_ids.py
