comment: false
coverage:
  status:
    patch:
      default:
        target: auto
    project:
      default:
        target: auto
ignore:
  - credentials/settings/production.py
  - credentials/settings/devstack.py
