version: "2"

services:
  credentials:
    volumes:
      - .:/edx/app/credentials/credentials
    # The docker container produced by configuration.git does not currently
    # run and expose a port for credentials. This means that we need to run some
    # command that keeps the credentials container alive while we run tests on it.
    # We have not yet standardized on an init replacement which could be used instead.
    command: tail -f /dev/null
    environment:
      - CONN_MAX_AGE=60
      - DB_ENGINE=django.db.backends.mysql
      - DB_HOST=db
      - DB_NAME=credentials
      - DB_PASSWORD=password
      - DB_PORT=3306
      - DB_USER=credentials001
      - DJANGO_SETTINGS_MODULE=credentials.settings.test
      - ENABLE_DJANGO_TOOLBAR=1
