version: "2"

services:
  db:
    ports:
      - "3306:3306"

  credentials:
    volumes:
      - .:/edx/app/credentials/credentials
      - /edx/app/credentials/credentials/credentials/assets
      - /edx/app/credentials/credentials/node_modules
