@startuml name "Verifiable Credentials"

title "Full issuance process (mobile wallet)"

autonumber

actor           Learner as learner
box "Open edX"
participant     "Learner Record MFE" as mfe
participant     "Credentials IDA\n(verifiable_credentials)" as credentials
end box
box "Storage Backends"
participant     "Mobile Wallet" as mobile
end box

learner -> mfe : Opens tab \n"Verifiable Credentials"

mfe -> credentials : Fetch Learner's program certificates
mfe <-- credentials : UserCredential data list

rnote over mfe: Program Certificate cards displayed

mfe -> credentials : Fetch available storages
mfe <-- credentials : storages configuration

alt a single storage special case
    rnote over mfe: "Create" button rendered
    learner -> mfe : Clicks "Create" button
else multiple storage case
    rnote over mfe: "Create with..." dropdown rendered
    learner -> mfe : Clicks "Create with..." dropdown and\npicks a desired storage/wallet
end

mfe -> credentials : Issuance initialization\n POST "/init/: {credential ID, storage ID}

rnote over credentials: Issuance line created: \n- UserCredential association \n- Storage backend resolved \n- Issuer resolved \n- Data model resolved \n- Deep-link generated

mfe <-- credentials : Backend-specific data \n{deep-link, QR code, apps download links}

alt mobile client
    rnote over mfe: Displays modal with:\n- deeplink button \n- apps download links \n- additional instructions
    rnote over learner : Optionally downloads, \ninstalls mobile application
    learner -> mfe : Clicks "Download Credential"
else web client
    rnote over mfe: Displays modal with:\n- **QR code** \n- deeplink button \n- apps download links \n- additional instructions
    rnote over learner : Optionally downloads, \ninstalls mobile application
    learner -> mfe : Scans QR code with mobile application
end

mfe -> mobile : Deeplink initiates mobile openning

rnote over mobile: Storage process deeplink params \nand composes issuance request

credentials <- mobile : Verifiable credential issuance request\n POST "/issue/: {issuance line ID}
rnote over credentials: Issuance process: \n- request validation \n- issuance line update \n- gathering data \n- credential document composition \n- document signing \n- serialization
credentials --> mobile : Verifiable credential returned

@enduml