# Generated by Django 3.2.19 on 2023-06-26 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid

from credentials.apps.verifiable_credentials.issuance.utils import create_issuers


def make_default_issuers(apps, schema_editor):
    create_issuers()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    """
    Squash after the initial development.
    """

    replaces = [
        ("verifiable_credentials", "0001_initial"),
        ("verifiable_credentials", "0002_verifiablecredentialissuance"),
        ("verifiable_credentials", "0003_auto_20230216_1508"),
        ("verifiable_credentials", "0004_auto_20230217_1550"),
        ("verifiable_credentials", "0005_auto_20230218_1816"),
        ("verifiable_credentials", "0006_auto_20230305_1318"),
        ("verifiable_credentials", "0007_auto_20230312_1011"),
        ("verifiable_credentials", "0008_auto_20230312_1633"),
        ("verifiable_credentials", "0009_auto_20230326_0925"),
        ("verifiable_credentials", "0010_data_create_default_issuers"),
        ("verifiable_credentials", "0011_auto_20230405_0915"),
    ]

    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("credentials", "0025_change_usercredentialdateoverride_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0015_auto_20201130_2041"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuanceLine",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(
                        default=False, help_text="Completeness indicator"
                    ),
                ),
                ("issuer_id", models.CharField(help_text="Issuer DID", max_length=255)),
                (
                    "storage_id",
                    models.CharField(
                        help_text="Target storage identifier", max_length=128
                    ),
                ),
                (
                    "user_credential",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related Open edX learner credential",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vc_issues",
                        to="credentials.usercredential",
                    ),
                ),
                (
                    "subject_id",
                    models.CharField(
                        default="change-me",
                        help_text="Verifiable credential subject DID",
                        max_length=255,
                    ),
                ),
                (
                    "data_model_id",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vc", "Verifiable Credentials Data Model v1.1"),
                            ("obv3", "Open Badges Specification v3.0"),
                            ("status-list-2021", "Status List 2021"),
                        ],
                        help_text="Verifiable credential specification to use",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="Keeps track on a corresponding user credential's status",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status_index",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Defines a position in the Status List sequence",
                        null=True,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IssuanceConfiguration",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "issuer_id",
                    models.CharField(
                        help_text="Issuer DID",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "issuer_key",
                    models.JSONField(
                        help_text="Issuer secret key. See: https://w3c-ccg.github.io/did-method-key/#ed25519-x25519"
                    ),
                ),
                (
                    "issuer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "ordering": ["enabled"],
            },
        ),
        migrations.RunPython(
            code=make_default_issuers,
            reverse_code=reverse,
        ),
        migrations.AlterModelOptions(
            name="issuanceconfiguration",
            options={"ordering": ("enabled", "created")},
        ),
        migrations.AlterModelOptions(
            name="issuanceline",
            options={"ordering": ("created",)},
        ),
        migrations.AlterUniqueTogether(
            name="issuanceline",
            unique_together={("issuer_id", "status_index")},
        ),
    ]
