# Generated by Django 3.2.21 on 2023-09-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifiable_credentials', '0001_initial_20230626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuanceline',
            name='subject_id',
            field=models.CharField(help_text='Verifiable credential subject DID', max_length=255),
        ),
    ]
