# Generated by Django 4.2.5 on 2023-09-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verifiable_credentials", "0001_initial_20230626"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuanceline",
            name="subject_id",
            field=models.CharField(help_text="Verifiable credential subject DID", max_length=255),
        ),
    ]
