# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-16 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180712_2016'),
        ('records', '0003_grades_username_mode_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcertrecord',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Program'),
        ),
    ]
