# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-17 20:02
from __future__ import unicode_literals

from django.db import migrations

from credentials.apps.catalog.models import Program
from credentials.apps.records.models import ProgramCertRecord


def seed_program_cert_records(apps, schema_editor):
    for pcr in ProgramCertRecord.objects.all():
        pcr.program = Program.objects.get(uuid=pcr.certificate.program_uuid)
        pcr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20180717_1953'),
    ]

    operations = [
        migrations.RunPython(seed_program_cert_records),
    ]
