# Generated by Django 1.11.11 on 2018-07-23 16:47


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20180723_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programcertrecord',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Program'),
        ),
    ]
