# Generated by Django 1.11.11 on 2018-07-24 18:21


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180712_2016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0008_auto_20180723_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreditPathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('sent', 'sent'), ('', 'other')], default='sent', max_length=15)),
                ('credit_pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.CreditPathway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usercreditpathway',
            unique_together={('user', 'credit_pathway')},
        ),
    ]
