# Generated by Django 1.11.11 on 2018-07-26 13:34


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_user_credit_pathway'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programcertrecord',
            options={'verbose_name': 'Shared Program Records'},
        ),
    ]
