# Generated by Django 1.11.11 on 2018-07-26 19:16


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20180726_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programcertrecord',
            options={'verbose_name': 'Shared program record'},
        ),
    ]
