# Generated by Django 1.11.11 on 2018-08-01 20:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_auto_20180726_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreditpathway',
            name='status',
            field=models.CharField(blank=True, choices=[('sent', 'sent'), ('', 'other')], default='sent', max_length=15),
        ),
    ]
