# Generated by Django 3.2.14 on 2022-08-09 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20201130_2041'),
        ('records', '0019_auto_20210405_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreditpathway',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.program'),
        ),
    ]
