# Generated by Django 3.2.14 on 2022-09-12 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0015_auto_20201130_2041'),
        ('records', '0019_auto_20210405_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreditpathway',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.program'),
        ),
        migrations.AlterUniqueTogether(
            name='usercreditpathway',
            unique_together={('user', 'pathway', 'program')},
        ),
    ]
