# Generated by Django 3.2.14 on 2022-09-08 20:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20201130_2041'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0020_usercreditpathway_program'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercreditpathway',
            unique_together={('user', 'pathway', 'program')},
        ),
    ]
