# Generated by Django 1.9.13 on 2017-04-20 16:51


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0009_remove_programcertificate_program_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertificateTemplateAsset',
        ),
        migrations.RemoveField(
            model_name='coursecertificate',
            name='template',
        ),
        migrations.RemoveField(
            model_name='programcertificate',
            name='template',
        ),
        migrations.DeleteModel(
            name='CertificateTemplate',
        ),
    ]
