# Generated by Django 1.11.15 on 2018-08-22 16:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('credentials', '0014_auto_20180816_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programcertificate',
            name='program_uuid',
            field=models.UUIDField(db_index=True, verbose_name='Program UUID'),
        ),
        migrations.AlterUniqueTogether(
            name='programcertificate',
            unique_together={('site', 'program_uuid')},
        ),
    ]
