# Generated by Django 2.2.15 on 2020-08-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0015_auto_20180822_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredential',
            name='credential_content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('coursecertificate', 'programcertificate')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
