# Generated by Django 2.2.17 on 2021-04-02 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_auto_20201130_2041"),
        ("credentials", "0017_historicalprogramcompletionemailconfiguration_programcompletionemailconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="programcertificate",
            name="program",
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to="catalog.Program"),
        ),
    ]
