# Generated by Django 2.2.17 on 2021-04-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_auto_20201130_2041"),
        ("credentials", "0019_populate_program_on_program_cert"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecertificate",
            name="course_run",
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to="catalog.CourseRun"),
        ),
    ]
