# Generated by Django 2.2.17 on 2021-04-07 17:58

from django.db import migrations


def populate_course_run(apps, schema_editor):
    CourseRun = apps.get_model("catalog", "CourseRun")
    CourseCertificate = apps.get_model("credentials", "CourseCertificate")
    for course_cert in CourseCertificate.objects.all():
        try:
            course_run = CourseRun.objects.get(key=course_cert.course_id)
        except CourseRun.DoesNotExist:
            continue
        course_cert.course_run = course_run
        course_cert.save()


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0020_coursecertificate_course_run"),
    ]

    operations = [migrations.RunPython(populate_course_run)]
