# Generated by Django 2.2.20 on 2021-04-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0021_auto_20210407_1758"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecertificate",
            name="certificate_available_date",
            field=models.DateTimeField(
                default=None,
                help_text="The certificate available time that is set in Studio and copied to Credentials.",
                null=True,
            ),
        ),
    ]
