# Generated by Django 2.2.24 on 2021-08-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0022_coursecertificate_certificate_available_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecertificate",
            name="certificate_type",
            field=models.CharField(
                choices=[
                    ("honor", "honor"),
                    ("professional", "professional"),
                    ("verified", "verified"),
                    ("no-id-professional", "no-id-professional"),
                    ("masters", "masters"),
                ],
                max_length=255,
            ),
        ),
    ]
