# Generated by Django 2.2.24 on 2021-09-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0024_usercredentialdateoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredentialdateoverride',
            name='date',
            field=models.DateTimeField(help_text='The date to override a course certificate with. This is set in the LMS Django Admin.'),
        ),
    ]
