# Generated by Django 3.2.20 on 2024-03-13 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('credentials', '0025_change_usercredentialdateoverride_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredential',
            name='credential_content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('coursecertificate', 'programcertificate', 'badgetemplate')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
