# Generated by Django 3.2.16 on 2022-12-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0025_change_usercredentialdateoverride_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signatory',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
