# Generated by Django 4.2.5 on 2023-09-20 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("credentials", "0026_alter_historicalprogramcompletionemailconfiguration_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalprogramcompletionemailconfiguration",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical program completion email configuration",
            },
        ),
    ]
