# Generated by Django 3.2.20 on 2024-04-08 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('credentials', '0026_alter_usercredential_credential_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredential',
            name='credential_content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('coursecertificate', 'programcertificate', 'credlybadgetemplate')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='usercredential',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
