# Generated by Django 3.2.16 on 2022-12-26 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20201130_2041'),
        ('credentials', '0026_alter_signatory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecertificate',
            name='course_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.courserun'),
        ),
    ]
