# Generated by Django 3.2.20 on 2024-04-16 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0027_auto_20240408_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredential',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
