# Generated by Django 4.2.6 on 2023-10-13 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("credentials", "0027_alter_historicalprogramcompletionemailconfiguration_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalprogramcompletionemailconfiguration",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical program completion email configuration",
                "verbose_name_plural": "historical program completion email configurations",
            },
        ),
    ]
