# Generated by Django 3.2.24 on 2024-05-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0028_alter_historicalprogramcompletionemailconfiguration_options'),
        ('credentials', '0028_alter_usercredential_uuid'),
    ]

    operations = [
    ]
