# Generated by Django 4.2.13 on 2024-07-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0028_alter_historicalprogramcompletionemailconfiguration_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecertificate",
            name="signatories",
            field=models.ManyToManyField(blank=True, to="credentials.signatory"),
        ),
    ]
