# Generated by Django 4.2.17 on 2025-01-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0030_revoke_certificates_management_command"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercredential",
            name="credential_id",
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
