# Generated by Django 4.2.17 on 2025-02-13 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('credentials', '0031_usercredential_explicit_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredential',
            name='credential_content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('coursecertificate', 'programcertificate', 'credlybadgetemplate', 'accrediblegroup')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
