# Generated by Django 4.2.20 on 2025-04-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0032_alter_usercredential_credential_content_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercredential",
            name="download_url",
        ),
    ]
