# Generated by Django 5.2.7 on 2026-03-27 13:20

import credentials.apps.credentials.models
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_pathway_status_never_empty'),
        ('credentials', '0033_remove_download_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('description', models.TextField(help_text="Human-readable description of this asset (e.g. 'FBR Pakistan org logo – PNG 200×200').")),
                ('asset', models.FileField(help_text='Upload an image (PNG/SVG/JPG), CSS file, or font file (TTF/WOFF/WOFF2).', upload_to=credentials.apps.credentials.models.certificate_asset_path)),
                ('slug', models.SlugField(help_text="Unique identifier used to reference this asset in templates via {% certificate_asset_url 'your-slug' %}.", max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Certificate Asset',
                'verbose_name_plural': 'Certificate Assets',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ProgramCertificateTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('program_type', models.CharField(blank=True, default='', help_text='Program type name (e.g. "FBR Program"). Used when program_certificate is not set.', max_length=255)),
                ('template', models.TextField(help_text="Django template HTML. Must extend 'credentials/programs/base.html'. Override blocks: accomplishment_summary, accomplishment_stamp_title, background_watermark, background_logo, platform_logo.")),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, help_text='If set, applies only to programs from this organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_templates', to='catalog.organization')),
                ('program_certificate', models.ForeignKey(blank=True, help_text='If set, applies only to this specific program certificate.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_templates', to='credentials.programcertificate')),
            ],
            options={
                'verbose_name': 'Program Certificate Template',
                'verbose_name_plural': 'Program Certificate Templates',
                'ordering': ['-created'],
            },
        ),
    ]
