# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-06 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170215_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_template_code',
            field=models.TextField(blank=True, null=True, verbose_name='Footer Template'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_template_code',
            field=models.TextField(blank=True, null=True, verbose_name='Header Template'),
        ),
    ]
