# Generated by Django 4.2.6 on 2023-10-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_alter_user_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name="Full Name"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_staff", "is_superuser", "is_active"], name="core_user_is_staf_c26715_idx"),
        ),
    ]
