version: "2"

services:
  db:
    image: mysql:5.6
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "credentials001"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "credentials"

  memcache:
    image: memcached:1.4.24
    container_name: memcache

  credentials:
    # Uncomment this line to use the official credentials base image
    image: edxops/credentials:latest

    # Uncomment the next two lines to build from a local configuration repo
    #build: ../configuration
    #dockerfile: docker/build/credentials/Dockerfile

    container_name: credentials
    volumes:
      - ..:/edx/app/credentials/credentials
    command: tail -f /dev/null
    depends_on:
      - "db"
      - "memcache"
