# Generated by Django 3.2.20 on 2024-03-13 13:35

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0025_change_usercredentialdateoverride_date'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('credential', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credentials.usercredential')),
            ],
            options={
                'verbose_name_plural': 'badge progress records',
            },
        ),
        migrations.CreateModel(
            name='BadgeRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Public signal type. Use namespaced types, e.g: "org.openedx.learning.student.registration.completed.v1"', max_length=255)),
                ('effect', models.CharField(choices=[('award', 'award'), ('revoke', 'revoke')], default='award', help_text='Defines how this requirement contributes to badge earning.', max_length=32)),
                ('description', models.TextField(blank=True, help_text='Provide more details if needed.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badges.badgeprogress')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='badges.badgerequirement')),
            ],
        ),
        migrations.CreateModel(
            name='DataRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Public signal\'s data payload nested property path, e.g: "user.pii.username".', max_length=255, verbose_name='key path')),
                ('operator', models.CharField(choices=[('eq', '=')], default='eq', help_text='Expected value comparison operator. https://docs.python.org/3/library/operator.html', max_length=32, verbose_name='action')),
                ('value', models.CharField(help_text='Expected value for the nested property, e.g: "cucumber1997".', max_length=255, verbose_name='expected value')),
                ('requirement', models.ForeignKey(help_text='Parent requirement for this data rule.', on_delete=django.db.models.deletion.CASCADE, to='badges.badgerequirement')),
            ],
        ),
        migrations.CreateModel(
            name='BadgeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_active', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique badge template ID.', unique=True)),
                ('name', models.CharField(help_text='Badge template name.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Badge template description.', null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badge_templates/icons')),
                ('origin', models.CharField(blank=True, help_text='Badge template type.', max_length=128, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='badgerequirement',
            name='template',
            field=models.ForeignKey(help_text='Badge template this requirement serves for.', on_delete=django.db.models.deletion.CASCADE, to='badges.badgetemplate'),
        ),
        migrations.AddField(
            model_name='badgeprogress',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='badges.badgetemplate'),
        ),
    ]
