# Generated by Django 5.2.7 on 2026-09-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_accredibleapiconfig_accrediblebadge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='course_key',
            field=models.CharField(blank=True, help_text='Course key where this requirement was fulfilled', max_length=255, null=True),
        ),
    ]
