# Generated by Django 5.2.11 on 2026-08-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0002_accredibleapiconfig_accrediblebadge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="credlyorganization",
            name="authorization_token_issued_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current Credly authorization token was issued or last rotated.",
                null=True,
            ),
        ),
    ]
