# Generated by Django 3.2.20 on 2024-03-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_auto_20240330_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarule',
            name='operator',
            field=models.CharField(choices=[('eq', '=')], default='eq', help_text='Expected value comparison operator. https://docs.python.org/3/library/operator.html', max_length=32),
        ),
    ]
