# Generated by Django 4.2.17 on 2024-12-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0002_accredibleapiconfig_accrediblebadge_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accredibleapiconfig",
            name="name",
            field=models.CharField(help_text="Accredible API configuration name.", max_length=255, null=True),
        ),
    ]
