# Generated by Django 5.2.7 on 2026-08-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_accredibleapiconfig_accrediblebadge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credlyorganization',
            name='oauth_client_id',
            field=models.CharField(blank=True, help_text='OAuth 2.0 Client ID for Credly Organization.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='credlyorganization',
            name='oauth_client_secret',
            field=models.CharField(blank=True, help_text='OAuth 2.0 Client Secret for Credly Organization.', max_length=255, null=True),
        ),
    ]
