# Generated by Django 3.2.20 on 2024-04-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_alter_datarule_operator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datarule',
            unique_together={('requirement', 'data_path', 'operator', 'value')},
        ),
    ]
