# Generated by Django 3.2.20 on 2024-04-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_alter_datarule_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgerequirement',
            name='event_type',
            field=models.CharField(choices=[('org.openedx.learning.course.passing.status.updated.v1', 'org.openedx.learning.course.passing.status.updated.v1'), ('org.openedx.learning.ccx.course.passing.status.updated.v1', 'org.openedx.learning.ccx.course.passing.status.updated.v1')], help_text='Public signal type. Use namespaced types, e.g: "org.openedx.learning.student.registration.completed.v1"', max_length=255),
        ),
    ]
