# Generated by Django 3.2.20 on 2024-04-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0005_auto_20240403_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarule',
            name='operator',
            field=models.CharField(choices=[('eq', '='), ('ne', '!=')], default='eq', help_text='Expected value comparison operator. https://docs.python.org/3/library/operator.html', max_length=32),
        ),
    ]
