# Generated by Django 3.2.20 on 2024-04-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0006_auto_20240403_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgerequirement',
            name='effect',
        ),
    ]
