# Generated by Django 3.2.20 on 2024-04-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0007_remove_badgerequirement_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgerequirement',
            name='group',
            field=models.CharField(blank=True, help_text='Group ID for requirements grouping.', max_length=255, null=True),
        ),
    ]
