# Generated by Django 3.2.20 on 2024-04-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0008_badgerequirement_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgePenalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Provide more details if needed.', null=True)),
                ('requirements', models.ManyToManyField(help_text='Badge requirements for which this penalty is defined.', to='badges.BadgeRequirement')),
                ('template', models.ForeignKey(help_text='Badge template this penalty serves for.', on_delete=django.db.models.deletion.CASCADE, to='badges.badgetemplate')),
            ],
            options={
                'verbose_name_plural': 'Badge penalties',
            },
        ),
        migrations.CreateModel(
            name='PenaltyDataRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_path', models.CharField(help_text='Public signal\'s data payload nested property path, e.g: "user.pii.username".', max_length=255, verbose_name='key path')),
                ('operator', models.CharField(choices=[('eq', '='), ('ne', '!=')], default='eq', help_text='Expected value comparison operator. https://docs.python.org/3/library/operator.html', max_length=32)),
                ('value', models.CharField(help_text='Expected value for the nested property, e.g: "cucumber1997".', max_length=255, verbose_name='expected value')),
                ('penalty', models.ForeignKey(help_text='Parent penalty for this data rule.', on_delete=django.db.models.deletion.CASCADE, to='badges.badgepenalty')),
            ],
            options={
                'unique_together': {('penalty', 'data_path', 'operator', 'value')},
            },
        ),
    ]
