# Generated by Django 3.2.20 on 2024-04-10 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0010_auto_20240409_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penaltydatarule',
            name='penalty',
            field=models.ForeignKey(help_text='Parent penalty for this data rule.', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='badges.badgepenalty'),
        ),
    ]
