# Generated by Django 3.2.20 on 2024-04-12 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0011_auto_20240410_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgerequirement',
            name='event_type',
            field=models.CharField(choices=[('org.openedx.learning.course.passing.status.updated.v1', 'org.openedx.learning.course.passing.status.updated.v1'), ('org.openedx.learning.ccx.course.passing.status.updated.v1', 'org.openedx.learning.ccx.course.passing.status.updated.v1')], help_text='Public signal type. Available events are configured in "BADGES_CONFIG" setting. The crucial aspect for event to carry UserData in its payload.', max_length=255),
        ),
        migrations.AlterField(
            model_name='badgerequirement',
            name='group',
            field=models.CharField(blank=True, help_text='Optional. Requirements with identical Group ID become interchangeable (OR processing logic applies).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='badgerequirement',
            name='template',
            field=models.ForeignKey(help_text='Badge template this requirement serves for.', on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='badges.badgetemplate'),
        ),
    ]
