# Generated by Django 3.2.20 on 2024-04-15 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0012_auto_20240412_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarule',
            name='requirement',
            field=models.ForeignKey(help_text='Parent requirement for this data rule.', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='badges.badgerequirement'),
        ),
    ]
