# Generated by Django 3.2.20 on 2024-04-16 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0013_alter_datarule_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillment',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillments', to='badges.badgerequirement'),
        ),
    ]
