# Generated by Django 3.2.20 on 2024-04-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0014_alter_fulfillment_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='credlybadge',
            name='external_uuid',
            field=models.UUIDField(blank=True, help_text='Credly service badge identifier', null=True, unique=True),
        ),
    ]
