# Generated by Django 3.2.20 on 2024-04-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0016_rename_credential_badgeprogress_user_credential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeprogress',
            name='user_credential',
        ),
    ]
