# Generated by Django 3.2.20 on 2024-04-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0017_remove_badgeprogress_user_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgerequirement',
            name='group',
            field=models.CharField(blank=True, help_text='Optional. Put requirements into the same arbitrary Group ID to make them interchangeable (OR processing logic applies).', max_length=255, null=True),
        ),
    ]
