# Generated by Django 3.2.20 on 2024-05-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0019_fulfillment_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgepenalty',
            name='description',
        ),
    ]
