# Generated by Django 3.2.20 on 2024-05-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0020_remove_badgepenalty_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credlyorganization',
            name='api_key',
            field=models.CharField(blank=True, help_text='Credly API shared secret for Credly Organization.', max_length=255),
        ),
    ]
