# Generated by Django 4.1 on 2024-05-31 13:46

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0021_alter_credlyorganization_api_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fulfillment",
            old_name="group",
            new_name="blend",
        ),
        migrations.RemoveField(
            model_name="badgerequirement",
            name="group",
        ),
        migrations.AddField(
            model_name="badgerequirement",
            name="blend",
            field=models.CharField(
                blank=True,
                help_text="Optional. Group requirements together using the same Group ID for interchangeable (OR processing logic).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="badgetemplate",
            name="state",
            field=model_utils.fields.StatusField(
                choices=[("draft", "draft"), ("active", "active"), ("archived", "archived")],
                default="draft",
                help_text="Credly badge template state (auto-managed).",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
        migrations.AlterField(
            model_name="credlybadge",
            name="state",
            field=model_utils.fields.StatusField(
                choices=[
                    ("created", "created"),
                    ("no_response", "no_response"),
                    ("error", "error"),
                    ("pending", "pending"),
                    ("accepted", "accepted"),
                    ("rejected", "rejected"),
                    ("revoked", "revoked"),
                    ("expired", "expired"),
                ],
                default="created",
                help_text="Credly badge issuing state",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
    ]
