# Generated by Django 1.11.11 on 2018-06-25 18:27


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='type',
            field=models.CharField(default='', max_length=32),
        ),
    ]
