# Generated by Django 1.11.15 on 2018-08-27 14:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_program_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='pathway_type',
            field=models.CharField(choices=[('CREDIT', 'credit'), ('INDUSTRY', 'industry')], default='credit', max_length=255),
        ),
    ]
