# Generated by Django 1.11.15 on 2018-08-28 13:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_pathway_pathway_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathway',
            name='pathway_type',
            field=models.CharField(choices=[('credit', 'credit'), ('industry', 'industry')], default='credit', max_length=32),
        ),
    ]
