# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-30 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180828_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courserun',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='courserun',
            old_name='start',
            new_name='start_date',
        ),
    ]
