# Generated by Django 1.11.25 on 2019-10-31 18:08


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_courserun_copy_column_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserun',
            name='end',
        ),
        migrations.RemoveField(
            model_name='courserun',
            name='start',
        ),
    ]
