# Generated by Django 2.2.17 on 2020-11-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_program_type_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='certificate_logo_image_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='total_hours_of_effort',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
