# Generated by Django 3.2.16 on 2022-10-11 12:23

from django.db import migrations


def forward(apps, schema_editor):
    return


def reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20201130_2041'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
