# Generated by Django 4.2.19 on 2025-02-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_auto_20201130_2041"),
    ]

    operations = [
        migrations.AddField(
            model_name="pathway",
            name="status",
            field=models.CharField(max_length=24, null=True),
        ),
    ]
