# Generated by Django 4.2.19 on 2025-02-28 16:28

from django.db import migrations, models
from django.db.models import Q


def populate_pathway_status(apps, schema_editor):
    Pathway = apps.get_model("catalog", "Pathway")
    for pathway in Pathway.objects.filter(Q(status__isnull=True) | Q(status__exact="")):
        pathway.status = "published"
        pathway.save()


def unpopulate_pathway_status(apps, schema_editor):
    """
    We must specify a backwards migration even if it is empty, or else django will raise an
    exception if we try to rollback this migration.

    We don't want to nullify everything that's published, because we don't know
    that's correct.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_pathway_status"),
    ]

    operations = [
        migrations.RunPython(populate_pathway_status, unpopulate_pathway_status),
        migrations.AlterField(
            model_name="pathway",
            name="status",
            field=models.CharField(
                choices=[("retired", "retired"), ("unpublished", "unpublished"), ("published", "published")],
                default="published",
                max_length=24,
            ),
        ),
    ]
