name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  quality_and_translations_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Dependencies
        run: make requirements
      - name: Install gettext
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y gettext
      - name: Run Tests
        run: |
          make check_translations_up_to_date
          make validate_translations
          make quality
          make check_keywords
          make pii_check

  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        django-version: ["django52"]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Setup Nodejs Env
        run: echo "NODE_VER=`cat .nvmrc`" >> $GITHUB_ENV
      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ env.NODE_VER }}
      - name: Install Dependencies
        run: make requirements
      - name: Install Firefox
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y firefox xvfb
      - name: Run Tests
        env:
          TOXENV: ${{ matrix.django-version }}
        run: |
          make static
          make tests
      - name: Run code coverage
        if: matrix.python-version == '3.12' && matrix.django-version == 'django42'
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          flags: unittests
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Dependencies
        run: make requirements
      - name: Build the docs
        run: make docs
